name: Verify RT MSRV

on:
  push:
    paths:
      - .github/workflows/verify-msrv.yml

jobs:
  msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust 1.63
        run: |
          rustup toolchain install 1.63.0 --profile minimal
          rustup override set 1.63.0
          rustc --version
          cargo --version
      - name: Build and test
        run: |
          cargo test
          cargo build --release
          echo 'Rust 1.63 verification passed.'
